version: '3.7'

services:
  web:
    build:
        context: ./web
        dockerfile: Dockerfile.prod
    command: gunicorn jd_quyy_hz.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8080:8080
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
