version: '3.7'

services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
